Repository SeattleColleges/nsc-events-nestjs, pull requests merged in 2023-11, with the labels that each got.

#35 nsc-events-nestjs_Sprint-5_Restrict-Access-to-User-Routes_34
  src/user/controllers/user/user.controller.spec.ts
  src/user/controllers/user/user.controller.ts
Labels: enhancement

#42 nsc-events_3_39_update-user-dto-refactor
  package-lock.json
  src/user/controllers/user/user.controller.spec.ts
  src/user/controllers/user/user.controller.ts
  src/user/dto/update-user.dto.ts
  src/user/services/user/user.service.ts
Labels: enhancement, Sprint 3

#43 NSC-Events_3_38_user-unit-tests
  src/user/controllers/user/user.controller.spec.ts
  src/user/controllers/user/user.controller.ts
  src/user/services/user.service.spec.ts
  src/user/services/user/user.service.ts
  src/user/user.module.ts
Labels: enhancement, Sprint 3

#45 nsc-events-nestjs-3-55-add-ishidden-property
  .env.sample
  package-lock.json
  package.json
  src/activity/controllers/activity/activity.controller.ts
  src/activity/dto/create-activity.dto.ts
  src/activity/dto/update-activity.dto.ts
  src/activity/schemas/activity.schema.ts
  src/activity/services/activity/activity.service.spec.ts
  src/activity/services/activity/activity.service.ts
  test/mock-data/createMockActivity.ts
Labels: enhancement, Sprint 3

#47 nsc_nestjs_enhancement_46_forgot-password
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/auth/dto/forgot-password.dto.ts
Labels: enhancement

#50 nsc_events_nestjs_4_116_add_appropriate_mit_licensing-to-each_repository
  LICENSE
  LICENSE.md
Labels: documentation, Sprint 4

#48 NSC-events-nest.js_01-132-error-handling-methods
  src/activity/controllers/activity/activity.controller.ts
  src/activity/services/activity/activity.service.spec.ts
  src/activity/services/activity/activity.service.ts
Labels: enhancement, Sprint 4

#55 nsc-events-nestjs-04-166-error-handling-signup-method
  src/auth/auth.service.ts
Labels: Sprint 4
