Repository SeattleColleges/nsc-events-nestjs, pull requests merged in 2023-12, with the labels that each got.

#54 nsc-events-nestjs_4_53_auth-controller-unit-test
  package-lock.json
  package.json
  src/auth/auth.module.ts
  src/auth/controllers/auth.controller.spec.ts
  src/auth/controllers/auth.controller.ts
Labels: Sprint 4

#59 Nsc events android 3 97 attend button
  src/activity/controllers/activity/activity.controller.ts
  src/activity/dto/attend-event.dto.ts
  src/activity/schemas/activity.schema.ts
  src/activity/services/activity/activity.service.ts
Labels: enhancement, Sprint 4, Sprint 5

#62 nsc-events-nestjs_4_60_auth-service-unit-test-pr2
  src/auth/auth.module.ts
  src/auth/controllers/auth.controller.spec.ts
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.spec.ts
  src/auth/services/auth.service.ts
Labels: enhancement
