Repository SeattleColleges/nsc-events-nestjs, pull requests merged in 2024-03, with the labels that each got.

#94 nsc-events-nestjs_4_93_delete_find_stale_templates
  pull_request_template.md
Labels: bug, Sprint 4

#92 nsc-events-nestjs-4-91-updating-backend-schema
  src/activity/controllers/activity/activity.controller.spec.ts
  src/activity/dto/create-activity.dto.ts
  src/activity/dto/update-activity.dto.ts
  src/activity/schemas/activity.schema.ts
  test/mock-data/createMockActivity.ts
  test/mock-data/returned-mock-activity.ts
Labels: enhancement, Sprint 4, USER STORY

#97 nsc-events-nextjs _ 4 _ 95 _ change-password-Page
  src/auth/controllers/auth.controller.ts
  src/auth/dto/change-password.dto.ts
  src/auth/services/auth.service.ts
Labels: enhancement, Sprint 4
