Repository SeattleColleges/nsc-events-nestjs, pull requests merged in 2024-02, with the labels that each got.

#75 nsc-events-nestjs-2-74-create-templates-for-nestjs
  .github/issue.md
  .github/pull_request.md
  .github/user_story.md
Labels: Sprint 2

#77 nsc-events-nestjs-2-76-add-front-matter-to-nestjs
  .github/issue.md
  .github/pull_request.md
  .github/user_story.md
Labels: Sprint 2

#79 nsc-nestjs-enhancement-78-forget_password_feature
  package-lock.json
  package.json
  src/auth/controllers/auth.controller.spec.ts
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.spec.ts
  src/auth/services/auth.service.ts
Labels: enhancement

#82 nsc-events-nestjs-3-81-add-files-for-nestjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/pull_request.md
  .github/ISSUE_TEMPLATE/user_story.md
Labels: Sprint 3

#86 nsc-events-nextjs_3_84_add-pronouns-field
  src/activity/controllers/activity/activity.controller.spec.ts
  src/activity/services/activity/activity.service.spec.ts
  src/auth/controllers/auth.controller.spec.ts
  src/auth/dto/signup.dto.ts
  src/auth/schemas/userAuth.model.ts
  src/auth/schemas/userAuthSchema.ts
  src/auth/services/auth.service.spec.ts
  src/auth/services/auth.service.ts
  src/user/dto/create-user.dto.ts
  src/user/dto/update-user.dto.ts
  src/user/schemas/user.model.ts
  src/user/services/user.service.spec.ts
  src/user/services/user/user.service.ts
Labels: enhancement, Sprint 3

#85 Create ssh.yml
  .github/workflows/ssh.yml
Labels: Sprint 3
