Repository SeattleColleges/nsc-events-nestjs, pull requests merged in 2024-05, with the labels that each got.

#109 nsc-events-nestjs_6_108_getAllActivites_numEvents
  src/activity/controllers/activity/activity.controller.ts
  src/activity/services/activity/activity.service.ts
Labels: Sprint 6

#111 nsc-events-nestjs-6-110-remove-duplicate-GET-handler
  src/activity/controllers/activity/activity.controller.spec.ts
  src/activity/controllers/activity/activity.controller.ts
Labels: bug

#104 NSCEvents_NestJs_Sprint_5_Unit_Testing
  src/auth/controllers/auth.controller.spec.ts
  src/auth/controllers/auth.controller.ts
  src/auth/services/auth.service.spec.ts
  src/user/controllers/user/user.controller.spec.ts
Labels: Sprint 5

#117 nsc-events-nestjs-06-116_events_not_in_ascending_order
  src/activity/services/activity/activity.service.spec.ts
  src/activity/services/activity/activity.service.ts
Labels: bug, Sprint 6

#115 nsc-events-nestjs_7_114_enable-nestjs-auto-assign-issues
  .github/workflows/auto-assign-issues.yml
Labels: Sprint 6

#119 nsc-events-nestjs-7-118-refactor-getAllActivities-service-method
  src/activity/controllers/activity/activity.controller.spec.ts
  src/activity/controllers/activity/activity.controller.ts
  src/activity/services/activity/activity.service.spec.ts
  src/activity/services/activity/activity.service.ts
Labels: Sprint 7, refactor

#121 nsc-events-nestjs-7-120-update-get-events-by-user-id-controller
  src/activity/controllers/activity/activity.controller.ts
  src/activity/services/activity/activity.service.ts
Labels: Sprint 7, refactor
